(deftheme elmgrave
  "bright yet earthy")

(custom-theme-set-faces
 'elmgrave
 '(cursor ((t (:foreground "white smoke" :background "#fcce8d"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#222323"))))
 '(homoglyph ((t (:foreground "#222323"))))
 '(minibuffer-prompt ((t (:height 1.0 :weight bold :foreground "#f95142"))))
 '(highlight ((t (:background "#e9d6c5" :foreground "#1e1610"))))
 '(region ((t (:extend t :background "#fcce8d" :foreground "#1e1610"))))
 '(shadow ((t (:foreground "#d3ad8b"))))
 '(secondary-selection ((t (:extend t :background "#fcce8d"))))
 '(trailing-whitespace ((t (:background "#f95142"))))
 '(font-lock-builtin-face ((t (:foreground "#1f2f49"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#d3ad8b"))))
 '(font-lock-constant-face ((t (:foreground "#1e1610"))))
 '(font-lock-doc-face ((t (:foreground "#d3ad8b"))))
 '(font-lock-function-name-face ((t (:foreground "#ff8f46"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#4d7c71"))))
 '(font-lock-negation-char-face ((t (:foreground "#222323"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#84a3a5"))))
 '(font-lock-type-face ((t (:foreground "#f2bb4e"))))
 '(font-lock-variable-name-face ((t (:foreground "#1e1610"))))
 '(font-lock-warning-face ((t (:foreground "#1e1610" :background "#f95142"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#1e1610"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "RoyalBlue3"))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:background "#e9d6c5" :foreground "#1f2f49"))))
 '(header-line ((t (:inherit mode-line :background "#d3ad8b" :foreground "#1e1610" :box nil))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#d3ad8b" :foreground "#1e1610" :weight bold))))
 '(mode-line-buffer-id ((t (:foreground "#1e1610" :weight extra-bold))))
 '(mode-line-emphasis ((t (:foreground "#004c3d"))))
 '(mode-line-highlight ((t (:foreground "#405987" :weight bold))))
 '(mode-line-inactive ((t (:background "#e9d6c5" :foreground "#d3ad8b" :weight normal))))
 '(isearch ((t (:background "#4d7c71" :foreground "#fcce8d"))))
 '(isearch-fail ((t (:background "#f95142" :foreground "#1e1610"))))
 '(lazy-highlight ((t (:background "#e9d6c5" :foreground "#1e1610"))))
 '(match ((t (:background "#8dc196"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit isearch))))
 '(line-number-current-line ((t (:inherit line-number :background "#e9d6c5"))))
 '(show-paren-match ((t (:background "#fcce8d"))))
 '(show-paren-match-expression ((t (:inherit (show-paren-match)))))
 '(show-paren-mismatch ((t (:background "#f95142" :foreground "#f3ede3"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#f3ede3" :foreground "#1e1610" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Menlo"))))
 '(line-number ((t (:inherit (shadow default))))))

(provide-theme 'elmgrave)
